version: "3"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_DB=match
    expose:
      - "5432"
    networks:
      db_net:
        aliases:
          - database
    healthcheck:
      test: pg_isready -U postgres -d match
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - db_net
    volumes:
      - ./ent/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:@database:5432/match?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  seed:
    build:
      context: .
      dockerfile: Dockerfile.seed
    environment:
      - DB_USER=postgres
      - DB_NAME=match
      - DB_HOST=database
    networks:
      - db_net
    depends_on:
      - migrate
    profiles:
      - seed

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DB_USER=postgres
      - DB_NAME=match
      - DB_HOST=database
    # network_mode: "host"
    networks:
      - db_net
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - migrate

networks:
  db_net:
    driver: bridge
