-- create "partners" table
CREATE TABLE "partners" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "address" character varying NOT NULL, "rating" bigint NOT NULL, "radius_of_operation" double precision NOT NULL, PRIMARY KEY ("id"));
-- create "materials" table
CREATE TABLE "materials" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "material" character varying NOT NULL, PRIMARY KEY ("id"));
-- create "partner_materials" table
CREATE TABLE "partner_materials" ("partner_id" bigint NOT NULL, "material_id" bigint NOT NULL, PRIMARY KEY ("partner_id", "material_id"), CONSTRAINT "partner_materials_partner_id" FOREIGN KEY ("partner_id") REFERENCES "partners" ("id") ON DELETE CASCADE, CONSTRAINT "partner_materials_material_id" FOREIGN KEY ("material_id") REFERENCES "materials" ("id") ON DELETE CASCADE);
