// Code generated by ent, DO NOT EDIT.

package material

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/fbngrm/around-home/ent/predicate"
	"github.com/fbngrm/around-home/pkg/materials"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MaterialEQ applies the EQ predicate on the "material" field.
func MaterialEQ(v materials.Material) predicate.Material {
	vc := v
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMaterial), vc))
	})
}

// MaterialNEQ applies the NEQ predicate on the "material" field.
func MaterialNEQ(v materials.Material) predicate.Material {
	vc := v
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMaterial), vc))
	})
}

// MaterialIn applies the In predicate on the "material" field.
func MaterialIn(vs ...materials.Material) predicate.Material {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldMaterial), v...))
	})
}

// MaterialNotIn applies the NotIn predicate on the "material" field.
func MaterialNotIn(vs ...materials.Material) predicate.Material {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Material(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldMaterial), v...))
	})
}

// HasPartners applies the HasEdge predicate on the "partners" edge.
func HasPartners() predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PartnersTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PartnersTable, PartnersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPartnersWith applies the HasEdge predicate on the "partners" edge with a given conditions (other predicates).
func HasPartnersWith(preds ...predicate.Partner) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(PartnersInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PartnersTable, PartnersPrimaryKey...),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Material) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Material) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Material) predicate.Material {
	return predicate.Material(func(s *sql.Selector) {
		p(s.Not())
	})
}
