// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MaterialsColumns holds the columns for the "materials" table.
	MaterialsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "material", Type: field.TypeEnum, Enums: []string{"WOOD", "CARPET", "TILES"}},
	}
	// MaterialsTable holds the schema information for the "materials" table.
	MaterialsTable = &schema.Table{
		Name:       "materials",
		Columns:    MaterialsColumns,
		PrimaryKey: []*schema.Column{MaterialsColumns[0]},
	}
	// PartnersColumns holds the columns for the "partners" table.
	PartnersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "address", Type: field.TypeString},
		{Name: "rating", Type: field.TypeInt},
		{Name: "radius_of_operation", Type: field.TypeFloat64},
	}
	// PartnersTable holds the schema information for the "partners" table.
	PartnersTable = &schema.Table{
		Name:       "partners",
		Columns:    PartnersColumns,
		PrimaryKey: []*schema.Column{PartnersColumns[0]},
	}
	// PartnerMaterialsColumns holds the columns for the "partner_materials" table.
	PartnerMaterialsColumns = []*schema.Column{
		{Name: "partner_id", Type: field.TypeInt},
		{Name: "material_id", Type: field.TypeInt},
	}
	// PartnerMaterialsTable holds the schema information for the "partner_materials" table.
	PartnerMaterialsTable = &schema.Table{
		Name:       "partner_materials",
		Columns:    PartnerMaterialsColumns,
		PrimaryKey: []*schema.Column{PartnerMaterialsColumns[0], PartnerMaterialsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "partner_materials_partner_id",
				Columns:    []*schema.Column{PartnerMaterialsColumns[0]},
				RefColumns: []*schema.Column{PartnersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "partner_materials_material_id",
				Columns:    []*schema.Column{PartnerMaterialsColumns[1]},
				RefColumns: []*schema.Column{MaterialsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MaterialsTable,
		PartnersTable,
		PartnerMaterialsTable,
	}
)

func init() {
	PartnerMaterialsTable.ForeignKeys[0].RefTable = PartnersTable
	PartnerMaterialsTable.ForeignKeys[1].RefTable = MaterialsTable
}
