// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/fbngrm/around-home/ent/partner"
	"github.com/fbngrm/around-home/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	partnerFields := schema.Partner{}.Fields()
	_ = partnerFields
	// partnerDescAddress is the schema descriptor for address field.
	partnerDescAddress := partnerFields[0].Descriptor()
	// partner.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	partner.AddressValidator = partnerDescAddress.Validators[0].(func(string) error)
}
