// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Material is the predicate function for material builders.
type Material func(*sql.Selector)

// Partner is the predicate function for partner builders.
type Partner func(*sql.Selector)
